name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  semantic-pull-request:
    uses: ./.github/workflows/semantic-pull-request.yml@main
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: percebus/github-actions-compliance/.github/actions/semantic-pull-request@main
    #     # - uses: amannn/action-semantic-pull-request@v6
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  audit:
    uses: ./.github/workflows/dependency-review.yml
