name: Semantic Pull-Request

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      github_token:
        type: string
        description: GitHub token
        required: false

# NOTE: Set in final file
# permissions:
#   pull-requests: read
#
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  semantic-pull-request:
    name: Semantic Pull-Request
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-compliance/.github/actions/semantic-pull-request@main
