name: Semantic Pull-Request

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

# NOTE: Set on final calling workflow
#
# permissions:
#   pull-requests: read

jobs:
  semantic-pull-request:
    name: Semantic Pull-Request
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-compliance/.github/actions/semantic-pull-request@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
